# Generated by Django 4.1.7 on 2023-03-31 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evocation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, null=True)),
                ('password', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='datetime1',
        ),
    ]
